- hosts: elasticsearch
  gather_facts: no

  vars:
    s3_plugin_url: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-{{ elk_version }}.zip

  tasks:
  - name: Validate elasticsearch Version
    fail: msg="Invalid ELK Version"
    when: elk_version is undefined or not elk_version is match("\d+\.\d+\.\d+")

  - name: Get elasticsearch current version
    command: rpm -q elasticsearch --qf %{VERSION}
    args:
      warn: no
    changed_when: False
    register: version_found
  
  - name: Pre-download elasticsearch from local repo
    get_url:
      dest: /tmp/elasticsearch-{{elk_version}}-x86_64.rpm
      url: http://svrrpoprd01/rhel/elasticsearch-7/{{elk_version}}/elasticsearch-{{elk_version}}-x86_64.rpm
  
  - name: Download repository-s3 plugin
    vars:  
      HTTP_PROXY: http://svrtscmpr06:3128
      HTTPS_PROXY: http://svrtscmpr06:3128
    get_url: url={{ s3_plugin_url }} dest=/tmp/repository-s3-{{ elk_version }}.zip
    when: version_found.stdout is version_compare(elk_version, '<')
