---
- hosts: logstash
  gather_facts: no

  tasks:
  - name: Validate logstash Version
    fail: msg="Invalid ELK Version"
    when: elk_version is undefined or not elk_version is match("\d+\.\d+\.\d+")

  - name: Get logstash current version
    command: rpm -q logstash --qf %{VERSION}
    args:
      warn: no
    changed_when: False
    register: version_found

  - name: Pre-download logstash install package
    yum:
      name: logstash-{{ elk_version }}
      download_only: yes
    when: version_found.stdout is version_compare(elk_version, '<')

- hosts: elasticsearch
  gather_facts: no

  vars:
    s3_plugin_url: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-{{ elk_version }}.zip

  tasks:
  - name: Validate elasticsearch Version
    fail: msg="Invalid ELK Version"
    when: elk_version is undefined or not elk_version is match("\d+\.\d+\.\d+")

  - name: Get elasticsearch current version
    command: rpm -q elasticsearch --qf %{VERSION}
    args:
      warn: no
    changed_when: False
    register: version_found
  
  - name: Pre-download elasticsearch from local repo
    get_url:
      dest: /tmp/elasticsearch-{{elk_version}}-x86_64.rpm
      url: http://svrrpoprd01/rhel/elasticsearch-7/{{es_version}}/elasticsearch-{{elk_version}}-x86_64.rpm
  
  - name: Download repository-s3 plugin
    vars:  
      HTTP_PROXY: http://svrtscmpr06:3128
      HTTPS_PROXY: http://svrtscmpr06:3128
      get_url: url={{ s3_plugin_url }} dest=/tmp/repository-s3-{{ elk_version }}.zip
    when: version_found.stdout is version_compare(elk_version, '<')

- hosts: kibana
  gather_facts: no

  tasks:
  - name: Validate kibana Version
    fail: msg="Invalid ELK Version"
    when: elk_version is undefined or not elk_version is match("\d+\.\d+\.\d+")

  - name: Get kibana current version
    command: rpm -q kibana --qf %{VERSION}
    args:
      warn: no
    changed_when: False
    register: version_found

  #- name: Pre-download kibana install package
  #  yum:
  #    name: kibana-{{ elk_version }}
  #    download_only: yes
  #  when: version_found.stdout is version_compare(elk_version, '<')

  - name: Pre-download kibana from local repo
    get_url:
      dest: /tmp/kibana-{{elk_version}}-x86_64.rpm
      url: http://svrrpoprd01/rhel/elasticsearch-7/{{elk_version}}/elasticsearch-{{elk_version}}-x86_64.rpm
  